### PR TITLE
Created a setup.py

### PR DESCRIPTION
**Pull request by Ademan**
Right now basically all it's good for is pulling in dependencies automatically, but if you move code into packages, and add a top level script this will be much more useful.

### CODE REVIEW

**Comment by jminardi** [comment]
python-btsync should be added as a dependency as well:
https://github.com/jminardi/python-btsync

**Comment by Ademan** [comment]
Ah you're right, I didn't notice until I started testing stuff. Are you sure your python-btsync setup.py works? For me it didn't install anything.

**Comment by Ademan** [comment]
There we go, the current version pulls BTSync from https://github.com/ademan/python-btsync though. If you merge the python-btsync change I can safely point it at your repo.

**Comment by jminardi** [comment]
I've merged your other PR

**Comment by jminardi** [comment]
Merging this PR as is now, we can point it to my repo later.

**Pull request merged**
